name: cd
on:
 workflow_dispatch:
   inputs:
     MODE:
       required: true
       description: rollback or not
       type: choice
       options:
         - rollback
         - standard
       default: standard
     To:
       required: true
       type: string
jobs:
 rollback-or-echo:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout repository
     uses: actions/checkout@v4
     with:
      token: ${{ github.token }}
      fetch-depth: 0
   - name: rollback
     if: ${{ inputs.MODE == 'rollback'}}
     run: |
      git config user.name lemonpieee110
      git config user.emai lemonpie110@163.com
      git checkout env/stg
      git reset --hard ${{inputs.To}}
      git push origin env/stg --force
          
       
